[project]
name = "carma-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reflex>=0.6.8",
    "sqlmodel>=0.0.22",
]
